name: FlySpeedLimits
version: '1.0.0'
main: me.xginko.flyspeedlimits.FlySpeedLimits
authors: [ xGinko ]
description: ${project.description}
website: ${project.url}
api-version: '1.13'
folia-supported: true
softdepend:
  - packetevents

commands:
  speedlimit:
    usage: /speedlimit [ reload, version ]
    description: Speedlimit commands
    aliases:
      - slimit